
tasks:
  - name: Install dependencies
    before: |
      sudo apt update -y && sudo apt install -y mosquitto mosquitto-clients
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    command:
      mosquitto

vscode:
  extensions:
    - rust-lang.rust